server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
          uri: http://news.baidu.com
          predicates:
#            - Path=/payment/feign/timeout  #断言,路径相匹配的进行路由
            - Path=/mil #断言,路径相匹配的进行路由


eureka:
  instance:
    hostname: cloud-gateway-com.service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka


