server:
  port: 9003


spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.19:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719

feign:
  sentinel:
    enabled: true




