server:
  port: 8002


spring:
  application:
    name: cloud-payment-com.service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://10.130.20.230:30286/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: aYe6ngFhNc

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.gefuxing.springcloud.entities



eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    register-with-eureka: true
    fetchRegistry: true
    instance:
      instance-id: payment8002
      prefer-ip-address: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

