server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: gfx
    nacos:
      discovery:
        server-addr: 172.24.2.51:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.130.16.246:31015/seata_order
    username: root
    password: aYe6ngFhNc

feign:
  hystrix:
    enabled: false

ribbon:
  ConnectTimeout: 60000 # 连接超时时间(ms)
  ReadTimeout: 60000 # 通信超时时间(ms)

logging:
  level:
    io:
      seata: error

mybatis:
  mapperLocations: classpath:mapper/*.xml

